# Generated by Django 5.2.6 on 2025-09-27 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userauth',
            name='is_subscribed',
        ),
    ]
