# Generated by Django 5.2.6 on 2025-09-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_userauth_is_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
