# Generated by Django 5.2.6 on 2026-02-06 10:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ACCOUNT', 'Account'), ('PAYMENT', 'Payment'), ('SUPPORT', 'Support'), ('SYSTEM', 'System')], default='SYSTEM', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('for_admin', models.BooleanField(db_index=True, default=True)),
                ('archived', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_read'], name='notificatio_is_read_f70e89_idx'), models.Index(fields=['created_at'], name='notificatio_created_fcd7aa_idx'), models.Index(fields=['updated_at'], name='notificatio_updated_f4140b_idx'), models.Index(fields=['archived'], name='notificatio_archive_4798a4_idx')],
            },
        ),
    ]
