# Generated by Django 5.2.6 on 2026-02-06 10:07

import django.db.models.deletion
import spiral_journey.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Soundscape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('audio_file', models.FileField(upload_to='soundscapes/')),
                ('duration', models.PositiveIntegerField(help_text='Duration in seconds')),
                ('mood', models.CharField(choices=[('anxious', 'Anxious'), ('overwhelmed', 'Overwhelmed'), ('cant_sleep', "Can't Sleep"), ('need_calm', 'Need Calm'), ('study', 'Study'), ('relax', 'Relax')], db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spiral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('focus_point', models.CharField(blank=True, max_length=255)),
                ('duration', models.PositiveSmallIntegerField(default=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spirals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SpiralDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('journal_prompt', models.TextField(blank=True, null=True)),
                ('voice_title', models.CharField(blank=True, max_length=255, null=True)),
                ('voice_drop', models.FileField(blank=True, null=True, upload_to=spiral_journey.models.spiral_voice_upload_path)),
                ('is_active', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spiral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='spiral_journey.spiral')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('spiral', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='SpiralReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('text_response', models.TextField()),
                ('spiral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to='spiral_journey.spiral')),
                ('spiral_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to='spiral_journey.spiralday')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spiral_reflections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('spiral_day', 'user')},
            },
        ),
    ]
