# Generated by Django 5.2.6 on 2025-09-22 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Spiral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('focus_point', models.CharField(max_length=255)),
                ('duration', models.PositiveIntegerField(default=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spirals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpiralDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('day_number', models.PositiveIntegerField()),
                ('journal_prompt', models.TextField()),
                ('voice_drop', models.FileField(blank=True, null=True, upload_to='spiral_voice_drops/')),
                ('is_active', models.BooleanField(default=True)),
                ('spiral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='spiral_journey.spiral')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('spiral', 'day_number')},
            },
        ),
    ]
