# Generated by Django 5.2.6 on 2025-09-24 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiral_journey', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpriralReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('text_response', models.TextField()),
                ('spiral_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to='spiral_journey.spiralday')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spiral_reflections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('spiral_day', 'user')},
            },
        ),
    ]
