# Generated by Django 5.2.6 on 2025-09-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiral_journey', '0002_spriralreflection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spriralreflection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='spriralreflection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
