# Generated by Django 5.2.6 on 2025-09-24 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spiral_journey', '0003_alter_spriralreflection_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpriralReflection',
        ),
    ]
