# Generated by Django 5.2.6 on 2025-09-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiral_journey', '0005_spiralreflection'),
    ]

    operations = [
        migrations.AddField(
            model_name='spiralday',
            name='voice_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
