# Generated by Django 5.2.6 on 2025-09-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiral_journey', '0006_spiralday_voice_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='spiralday',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
