# Generated by Django 5.2.6 on 2025-09-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiral_journey', '0007_spiralday_is_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soundscape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('audio_file', models.FileField(upload_to='soundscapes/')),
                ('duration', models.PositiveIntegerField(help_text='Duration in seconds')),
                ('mood', models.CharField(choices=[('anxious', 'Anxious'), ('overwhelmed', 'Overwhelmed'), ('cant_sleep', "Can't Sleep"), ('need_calm', 'Need Calm'), ('study', 'Study'), ('relax', 'Relax')], db_index=True, max_length=20)),
            ],
        ),
    ]
