# Generated by Django 5.2.6 on 2025-09-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiral_journey', '0008_soundscape'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundscape',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='soundscape',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
