# Generated by Django 5.2.6 on 2025-10-04 05:14

import spiral_journey.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiral_journey', '0009_soundscape_created_at_soundscape_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spiral',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='spiral',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='spiral',
            name='duration',
            field=models.PositiveSmallIntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='spiral',
            name='focus_point',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='spiral',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='spiralday',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='spiralday',
            name='journal_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spiralday',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='spiralday',
            name='voice_drop',
            field=models.FileField(blank=True, null=True, upload_to=spiral_journey.models.spiral_voice_upload_path),
        ),
    ]
