# Generated by Django 5.2.6 on 2025-09-20 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDiscovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('social_media', 'Social Media'), ('ads', 'Ads'), ('app_store', 'App Store'), ('word_of_mouth', 'Word Of Mouth'), ('podcasts_media', 'Podcasts / Media'), ('therapist', 'Therapist / Medical Professional'), ('streaming_platforms', 'Streaming Platforms'), ('other', 'Other')], default='other', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discovery', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
